// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSQELo0d1t9F8U6L5WkI0RTYGTLzqKnU',
    appId: '1:1060998802575:android:7d4933cfaf89bbc4ad94fa',
    messagingSenderId: '1060998802575',
    projectId: 'trendbuy-551cc',
    databaseURL: 'https://trendbuy-551cc-default-rtdb.firebaseio.com',
    storageBucket: 'trendbuy-551cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy2t_fBXkB86BAtMss4l9lSVtcHyjtSYs',
    appId: '1:1060998802575:ios:68464b1b3588009dad94fa',
    messagingSenderId: '1060998802575',
    projectId: 'trendbuy-551cc',
    databaseURL: 'https://trendbuy-551cc-default-rtdb.firebaseio.com',
    storageBucket: 'trendbuy-551cc.firebasestorage.app',
    iosClientId: '1060998802575-0thdepv931ggk2hpblr3fgjs03cosgj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendBuy',
  );

}